"""Literal transverse pullback, two-shift elimination and canonical vector.

Per transverse component use E_y(z), with spatial shear generated by the
unit-Jacobian pullback y -> y+E_y(z). This fixes the factors independently
of the TT normalization and never imports a printed vector kinetic action.
"""

from functools import cache

import sympy as sp

from . import action


@cache
def literal_geometry():
    scale, lapse = sp.symbols("a N", positive=True)
    h, shear, shear_prime, shift_z = sp.symbols("h E_z E_z_prime shift_z", real=True)
    metric = scale**2*sp.Matrix([[1, 0, 0], [0, 1, shear], [0, shear, 1+shear**2]])
    metric_prime = 2*h*metric+sp.diff(metric, shear)*shear_prime
    # Only N^y_{,z} is nonzero. The spatial metric has no y dependence.
    shift_derivative = sp.zeros(3)
    shift_derivative[1, 2] = shift_z
    lie_metric = shift_derivative.T*metric+metric*shift_derivative
    extrinsic = metric.inv()*(metric_prime-lie_metric)/(2*lapse)
    invariant = sp.factor(sp.trace(extrinsic**2)-sp.trace(extrinsic)**2)
    return {"a": scale, "N": lapse, "h": h, "E_z": shear,
            "E_z_prime": shear_prime, "shift_z": shift_z,
            "metric": metric, "det_metric": sp.factor(metric.det()),
            "extrinsic_invariant": invariant,
            "expected_invariant": -6*h**2/lapse**2+(shear_prime-shift_z)**2/(2*lapse**2)}


@cache
def literal_potential():
    a, n, c, y = sp.symbols("a N c y", positive=True)
    beta = sp.symbols("beta0:5", real=True)
    shear, z = sp.symbols("relative_E_z z", real=True)
    # The two positive spatial roots have determinant y² and trace
    # y*sqrt(4+relative_E_z²); the untouched spatial root is y.
    generating = (1+c*z)*(1+y*z)*(1+y*sp.sqrt(4+shear**2)*z+y**2*z**2)
    poly = sp.Poly(generating, z)
    density = -2*n*a**3*sum(beta[i]*poly.nth(i) for i in range(5))
    quadratic = sp.factor(sp.diff(density, shear, 2).subs(shear, 0)/2)
    mu = 2*y*(beta[1]+beta[2]*(c+y)+beta[3]*c*y)
    return {"a": a, "N": n, "c": c, "y": y, "beta": beta,
            "relative_E_z": shear, "generating": generating,
            "literal_quadratic": quadratic, "mu": mu,
            "expected_quadratic": -n*a**3*mu/4}


@cache
def schur():
    A, B, K = sp.symbols("A B K", positive=True)
    C, D = sp.symbols("C_shift D_potential", real=True)
    eg, ef, sg, sf, relative = sp.symbols("E_g_prime E_f_prime shift_g shift_f relative_E", real=True)
    lag = A*K*(eg-sg)**2+B*K*(ef-sf)**2+C*(sf-sg)**2-D*K*relative**2
    solution = sp.solve((sp.diff(lag, sg), sp.diff(lag, sf)), (sg, sf), dict=True)[0]
    reduced = sp.factor(lag.subs(solution, simultaneous=True))
    kinetic = A*B*C*K/(A*B*K+(A+B)*C)
    return {"A": A, "B": B, "K": K, "C": C, "D": D,
            "L": lag, "shift_solution": solution, "reduced_L": reduced,
            "kinetic": kinetic, "expected_L": kinetic*(ef-eg)**2-D*K*relative**2}


@cache
def derive():
    d = action.derive()
    a, b, c, y, u, P, C = (d[key] for key in ("a", "b", "c", "y", "u", "P", "C_shift"))
    K = action.K
    A, B, mu = a**3/4, b**3/(4*c), y*P
    D = a**3*mu/4
    kinetic = sp.factor(A*B*C*K/(A*B*K+(A+B)*C))
    bare = sp.factor(D*K/kinetic)
    theta = sp.diff(kinetic, u)/(2*kinetic)
    pump = sp.diff(theta, u)+theta**2
    speed = (c+y)/(2*y)
    mass = mu*(1+c/y**3)
    return {"u": u, "c": c, "K": K, "A": A, "B": B, "C_shift": C,
            "D": D, "mu": mu, "kinetic": kinetic, "omega_bare_squared": bare,
            "mass_algebraic_squared": mass, "speed_squared": speed,
            "theta": theta, "normalization_pump": pump,
            "omega_canonical_squared": bare-pump,
            "canonical_scale": sp.sqrt(2*kinetic),
            "canonical_boundary_coefficient": -theta/2}


def checks():
    g, p, s, d = literal_geometry(), literal_potential(), schur(), derive()
    return {
        "literal_unit_Jacobian_pullback": sp.factor(g["det_metric"]-g["a"]**6),
        "literal_extrinsic_square": sp.factor(g["extrinsic_invariant"]-g["expected_invariant"]),
        "literal_relative_spatial_shear_potential": sp.factor(p["literal_quadratic"]-p["expected_quadratic"]),
        "literal_two_shift_schur": sp.factor(s["reduced_L"]-s["expected_L"]),
        "actual_bare_frequency": sp.factor(d["omega_bare_squared"]-d["mass_algebraic_squared"]
                                            -d["speed_squared"]*action.K/action.derive()["a"]**2),
    }


@cache
def center_checks():
    d = derive()
    u, c, K = d["u"], d["c"], action.K
    at = {u: 0, c: 4}
    return {
        "c4_center_kinetic": sp.factor(d["kinetic"].subs(at)-8*K/(3*(K+16))),
        "c4_center_bare_frequency": sp.factor(d["omega_bare_squared"].subs(at)-3*K/2-24),
        "c4_center_normalization_pump": sp.factor(d["normalization_pump"].subs(at)+(47*K-96)/(3*(K+16))),
        "c4_center_canonical_frequency": sp.factor(d["omega_canonical_squared"].subs(at)
                                                     -(9*K**2+382*K+2112)/(6*(K+16))),
        "c1_high_K_negative_kinetic_control": sp.factor(d["kinetic"].subs({u: 0, c: 1})
                                                         +128*K/(3*(K-192))),
    }


@cache
def inner_checks():
    """Fixed nonzero K and compact x only; not a rolling spectral gap."""
    d = derive()
    eps = sp.Symbol("epsilon", positive=True)
    x = sp.Symbol("x", real=True)
    at = {d["u"]: eps*x, d["c"]: 2+eps**2}
    kinetic = sp.factor(d["kinetic"].subs(at))
    pump = sp.factor(d["normalization_pump"].subs(at))
    bare = sp.factor(d["omega_bare_squared"].subs(at))
    return {
        "fixed_K_inner_kinetic": sp.factor(sp.limit(kinetic, eps, 0)-action.K/5),
        "fixed_K_inner_scaled_pump": sp.factor(sp.limit(eps**2*pump, eps, 0)),
        "fixed_K_inner_scaled_frequency": sp.factor(sp.limit(eps**2*(bare-pump), eps, 0)-80/(1+8*x**2)),
    }
